### ISSUE TITLE
free() do not work

### ISSUE THREAD

**Issue by daohsong** [dvdface/devicepool#1]
I run a demo like this :
```
from devicepool import Device, DevicePool

resource_list = [
	{
		'ip':	'192.168.1.1',
		'type': 'android'
	},
	
	{
		'ip':	'192.168.1.2',
		'type': 'ios'
	}
]
devicepool = DevicePool(resource_list)
dev = devicepool.get()
print(dev)
dev.free()
```
And the script do not exit until the default rent_time is over, even if I call free() function.
Environment：
Python: 3.9.1
devicepool: 4.0.0
老哥你这个free函数不起作用呀，麻烦你看看是我环境有问题还是别的啥。

**Comment by daohsong** [comment]
Sry I misunderstand the logic. It looks like Timer threads are still working after free() is called, which leads the demo cannot end automatically.
啊我搞错了，free()没问题，应该是主动调用了free函数后，资源是释放了，但是在get()里设置的Timer线程还在，所以程序没办法自动结束

**Comment by daohsong** [comment]
I delete line 149 to 153 in devicepool.py, and this handle my issue.
所以感觉devicepool.py这个文件的149到153行，其实可以删掉。因为Timer在Device初始化的时候已经设定Timer了，感觉这里有点重复。

**Comment by dvdface** [comment]
谢谢你的建议，我抽空看看

**Comment by dvdface** [comment]
> I delete line 149 to 153 in devicepool.py, and this handle my issue.
> 所以感觉devicepool.py这个文件的149到153行，其实可以删掉。因为Timer在Device初始化的时候已经设定Timer了，感觉这里有点重复。

是有点儿，不过我后面打算把它做成RPC的形式，客户端虽然启动一个定时器线程，但是如果客户端异常退出了，这个定时器线程不起作用的话，在服务器端还能通过这个线程把资源释回收回来

**Comment by dvdface** [comment]
> get()

这个线程不影响，资源释放了，它不会重复释放
之所以不通知他主动停止，主要是考虑后面会做成RPC的形式，这样的话就可以支持分布式执行了
